version: '3'
services:
  vault:
    build: docker/vault
    hostname: vault.docker
    volumes:
      - /etc/puppetlabs/puppet/ssl/certs/ca.pem:/vault/config/ca.pem
      - /etc/puppetlabs/puppet/ssl/certs/vault.docker.pem:/vault/config/cert.pem
      - /etc/puppetlabs/puppet/ssl/private_keys/vault.docker.pem:/vault/config/private_key.pem
    ports:
      - 8200:8200
      - 8201:8201
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: >
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/vault/config/cert.pem",
              "tls_key_file": "/vault/config/private_key.pem"
            }
          }
        }
      VAULT_ADDR: "https://vault.docker:8200"
      VAULT_CACERT: "/vault/config/ca.pem"
      VAULT_CLIENT_KEY: "/vault/config/private_key.pem"
      VAULT_CLIENT_CERT: "/vault/config/cert.pem"
    command: ["server"]

